In [11]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.optim import SGD
import matplotlib.pyplot as plt
import time

In [2]:
x = [[1,2], [3,4], [5,6], [7,8]]
y = [[3], [7], [11], [15]]

In [3]:
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [4]:
class MyDataset(Dataset):
    def __init__(self, x, y):
        self.x = torch.tensor(x).float()
        self.y = torch.tensor(y).float()
        
    def __len__(self):
        return len(self.x)
    
    def __getitem__(self, ix):
        return self.x[ix], self.y[ix]

In [5]:
ds = MyDataset(X, Y)

<ipython-input-4-90b5b63620f0>:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x = torch.tensor(x).float()
<ipython-input-4-90b5b63620f0>:4: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y = torch.tensor(y).float()


In [6]:
dl = DataLoader(ds, batch_size=2, shuffle=True)

In [7]:
for x,y in dl:
    print(x, y)

tensor([[7., 8.],
        [3., 4.]]) tensor([[15.],
        [ 7.]])
tensor([[5., 6.],
        [1., 2.]]) tensor([[11.],
        [ 3.]])


In [8]:
class MyNeuralNet (nn.Module):
    def __init__(self):
        super().__init__()
    
        self.input_to_hidden_layer = nn.Linear(2, 8)
        self.hidden_layer_activation = nn.ReLU()
        self.hidden_to_output_layer = nn.Linear(8,1)
        
    def forward(self, x):
        x = self.input_to_hidden_layer(x)
        x = self.hidden_layer_activation(x)
        x = self.hidden_to_output_layer(x)
        return x

In [10]:
my_net = MyNeuralNet()
loss_func = nn.MSELoss()
opt = SGD(my_net.parameters(), lr= 0.001)

In [12]:
loss_history = []
start = time.time()
for _ in range(50):
    for data in dl:
        x, y = data
        opt.zero_grad()
        loss_value = loss_func(my_net(x), y)
        loss_value.backward()
        opt.step()
        loss_history.append(loss_value)
end = time.time()
print(end - start)

1.0852088928222656


In [13]:
val_x = [[10,11]]
val_x = torch.tensor(val_x).float()

In [14]:
my_net(val_x)

tensor([[21.1465]], grad_fn=<AddmmBackward0>)