In [1]:
import torch

In [2]:
print(torch.__version__)

1.10.2


In [3]:
x = torch.tensor([[1,2]])
y = torch.tensor([[1], [2]])

In [4]:
print(x.shape)
print(y.shape)

torch.Size([1, 2])
torch.Size([2, 1])


In [5]:
x = torch.tensor([False, 1, 2.])
print(x)

tensor([0., 1., 2.])


In [6]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [8]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[0, 9, 6, 9],
        [1, 4, 7, 0],
        [0, 7, 4, 7]])

In [9]:
torch.rand((3,4))

tensor([[0.1075, 0.0939, 0.0135, 0.7939],
        [0.4441, 0.6713, 0.6995, 0.8659],
        [0.2243, 0.0937, 0.9542, 0.1383]])

In [10]:
torch.randn((3,4))

tensor([[-0.0688,  0.8833,  0.3253,  0.3797],
        [-0.9401, -1.6108,  0.2690,  0.0671],
        [-0.4319,  1.4102,  1.3028,  1.1086]])

In [11]:
sample1 = torch.tensor([2, 3, 1, 0])
sample1.shape

torch.Size([4])

In [12]:
sample1 = sample1.view(4,1)
sample1

tensor([[2],
        [3],
        [1],
        [0]])

In [17]:
x = torch.tensor([[1,2,3,4], [5,6,7,8]])
y = x.view(4,2)
print(torch.matmul(x, y))

tensor([[ 50,  60],
        [114, 140]])


In [18]:
print(x@y)

tensor([[ 50,  60],
        [114, 140]])


In [23]:
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=0)
print(x.shape, z.shape)

torch.Size([10, 10, 10]) torch.Size([20, 10, 10])


In [24]:
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=1)
print(x.shape, z.shape)

torch.Size([10, 10, 10]) torch.Size([10, 20, 10])


In [25]:
x = torch.randn(10,10,10)
z = torch.cat([x,x], axis=2)
print(x.shape, z.shape)

torch.Size([10, 10, 10]) torch.Size([10, 10, 20])


In [26]:
x = torch.arange(25).reshape(5,5)

In [27]:
x

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [28]:
print(x.max())

tensor(24)


In [29]:
print(x.max(dim=0))

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 4, 4, 4, 4]))


In [32]:
x = torch.tensor([[ 0,  1,  2,  3,  4],
                    [ 5,  21,  7,  8,  9],
                    [10, 11, 12, 13, 14],
                    [15, 16, 17, 23, 19],
                    [20, 6, 22, 18, 24]])

In [33]:
print(x.max(dim=0))

torch.return_types.max(
values=tensor([20, 21, 22, 23, 24]),
indices=tensor([4, 1, 4, 3, 4]))


In [34]:
print(x.max(dim=1))

torch.return_types.max(
values=tensor([ 4, 21, 14, 23, 24]),
indices=tensor([4, 1, 4, 3, 4]))


In [36]:
x = torch.randn(10,20,30)
z = x.permute(2,0,1)
print(z.shape)

torch.Size([30, 10, 20])


In [38]:
sample2 = torch.randn(10,3)
print(sample2)

tensor([[ 0.8747, -0.8450, -0.6566],
        [-0.6228, -1.1005,  0.0823],
        [ 1.0649, -0.0441, -0.3547],
        [ 0.8272,  1.5046,  0.5281],
        [ 1.0218, -0.0681,  0.0128],
        [ 0.6088, -1.4636, -1.0020],
        [-1.2510, -1.2830, -2.3420],
        [-0.4426, -0.1653, -0.1445],
        [ 1.0691,  0.9296,  0.5939],
        [-0.6177, -0.5124,  0.2445]])


In [39]:
sample2.reshape(3,10)

tensor([[ 0.8747, -0.8450, -0.6566, -0.6228, -1.1005,  0.0823,  1.0649, -0.0441,
         -0.3547,  0.8272],
        [ 1.5046,  0.5281,  1.0218, -0.0681,  0.0128,  0.6088, -1.4636, -1.0020,
         -1.2510, -1.2830],
        [-2.3420, -0.4426, -0.1653, -0.1445,  1.0691,  0.9296,  0.5939, -0.6177,
         -0.5124,  0.2445]])

In [40]:
sample2.view(3,10)

tensor([[ 0.8747, -0.8450, -0.6566, -0.6228, -1.1005,  0.0823,  1.0649, -0.0441,
         -0.3547,  0.8272],
        [ 1.5046,  0.5281,  1.0218, -0.0681,  0.0128,  0.6088, -1.4636, -1.0020,
         -1.2510, -1.2830],
        [-2.3420, -0.4426, -0.1653, -0.1445,  1.0691,  0.9296,  0.5939, -0.6177,
         -0.5124,  0.2445]])

In [41]:
sample2.permute(1,0)

tensor([[ 0.8747, -0.6228,  1.0649,  0.8272,  1.0218,  0.6088, -1.2510, -0.4426,
          1.0691, -0.6177],
        [-0.8450, -1.1005, -0.0441,  1.5046, -0.0681, -1.4636, -1.2830, -0.1653,
          0.9296, -0.5124],
        [-0.6566,  0.0823, -0.3547,  0.5281,  0.0128, -1.0020, -2.3420, -0.1445,
          0.5939,  0.2445]])