In [1]:
import torch

In [2]:
print(torch.__version__)

1.10.2


In [3]:
x = torch.tensor([[1,2]])
y = torch.tensor([[1], [2]])

In [7]:
print(x.shape)
print(y.shape)

torch.Size([1, 2])
torch.Size([2, 1])


In [9]:
x = torch.tensor([False, 1, 2.])
print(x)

tensor([0., 1., 2.])


In [10]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [11]:
torch.ones((3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[3, 6, 1, 5],
        [6, 3, 4, 4],
        [3, 8, 9, 4]])

In [13]:
torch.rand((3,4))

tensor([[0.9633, 0.9121, 0.5842, 0.2245],
        [0.4135, 0.5698, 0.5145, 0.8915],
        [0.9923, 0.6899, 0.9542, 0.6802]])

In [14]:
torch.randn((3,4))

tensor([[-5.9362e-01,  1.0427e+00, -3.4300e-01, -6.1105e-01],
        [ 2.9375e+00, -1.1874e+00, -2.7369e+00,  1.7031e+00],
        [ 8.0453e-01, -8.7476e-01,  1.2663e-03, -2.3976e+00]])

In [15]:
sample1 = torch.tensor([2, 3, 1, 0])
sample1.shape

torch.Size([4])

In [17]:
sample1 = sample1.view(4,1)
sample1

tensor([[2],
        [3],
        [1],
        [0]])